name: Gradle

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x :test -x :ktlint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/out/test-results/test/TEST-*.xml'
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlint
      - uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        if: always() # always run even if the previous step fails
        with:
          path: '**/out/ktlint.xml'
          name: ktlint report
          title: ktlint report
  qodana:
    name: qodana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.1
        with:
          linter: jetbrains/qodana-jvm
          fail-threshold: 1
