name: Gradle
on:
  pull_request:
  push:
      branches:
        - master
        - main
jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-java@v1
      with:
        java-version: 16
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x :ktlint
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/out/test-results/test/TEST-*.xml'
  ktlint:
    name: ktlint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlint
